apiVersion: v1
kind: Pod
metadata:
  name: imagemagick-pod
spec:
  containers:
    - name: imagemagick-container
      image: jalexhurt/imagemagick
      command: ["sleep", "infinity"]
      resources:
        limits:
          memory: 4Gi
          cpu: 2
        requests:
          memory: 4Gi
          cpu: 2
